### PR TITLE
The 1st version of FPE, no LAX, parameters are in the constant.F file 

### PR DESCRIPTION
**Pull request by siwei-noaa**
This is a first try. I am trying to merge my changes to this repo. You can ignore the file change request since my **Makefile** and **user_build_options** are completely different from the HPC used. Also, some of changes are just format changes.

Since my code keep changing, I am not sure if this is the right time to merge. 

Thanks,
Siwei

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]
Changes in this commit are all good and could be merged.

**Review by tanyasmirnova — APPROVED** [review]

**Review by tanyasmirnova — COMMENTED** [review]
Siwei,
Do you need the test.txt file?
Tanya

**Review by tanyasmirnova — COMMENTED** [review]
Siwei,
Could you, please, make a separate Makefile for a laptop compiler, and also a laptop user_build_options, so that we do not overwrite the existing ones used on theia supercomputer?

**Review by tanyasmirnova — APPROVED** [review]
Siwei,
It looks this commit adds back Makefile and users_build_options that were deleted in the precious commit, right?

**Comment by siwei-noaa** [comment]
Yes, I have made two for myself. You can reject the changes on the GitHub since that was a mistake. I will not commit Makefile and user_build_options any more.

Thanks,
Siwei

**Review by tanyasmirnova — APPROVED** [review]
Changes in this commit are all good and could be merged.

**Pull request merged**
